apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    environment: dev
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkins: "https://www.jenkins.io/doc/book/installing/linux/"

spec:
  containers:
  - name: nginx
    image: nginx