apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
  resources:
    requests: # Soft Limits
      memory: "64M" #RAM
      cpu: "100m" #CPU
      
    limits: # Hard Limits
      memory: "128M"
      cpu: "150m"